### ISSUE TITLE
Unable to read shapefiles with Mercator projection

### ISSUE THREAD

**Issue by bchapuis** [Geomatys/geotoolkit#23] opened 2022-04-21 09:48 UTC
An exception occurs when reading the shapefiles files provided by [osmdata](https://osmdata.openstreetmap.de/data/water-polygons.html) that use a Mercator projection. Here are the steps to reproduce this issue.

The shapefile:
https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip

the content of the `.prj` file:
```
PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Mercator_Auxiliary_Sphere"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],PARAMETER["Standard_Parallel_1",0.0],PARAMETER["Auxiliary_Sphere_Type",0.0],UNIT["Meter",1.0]]
```

The code triggering the exception:

```java
ShapefileFeatureStore featureStore = 
    new ShapefileFeatureStore(URI.create("file:///tmp/simplified-water-polygons-split-3857/simplified_water_polygons.shp"));
featureStore.components();
```

The exception:
```
Apr 21, 2022 11:39:07 AM org.geotoolkit.data.shapefile.ShapefileFeatureStore buildSchema
WARNING: No operation method found for name or identifier “Mercator_Auxiliary_Sphere”.
org.geotoolkit.io.ContentFormatException: No operation method found for name or identifier “Mercator_Auxiliary_Sphere”.
	at org.geotoolkit.io.wkt.PrjFiles.read(PrjFiles.java:191)
	at org.geotoolkit.io.wkt.PrjFiles.read(PrjFiles.java:146)
	at org.geotoolkit.io.wkt.PrjFiles.read(PrjFiles.java:128)
	at org.geotoolkit.data.shapefile.ShapefileFeatureStore.buildSchema(ShapefileFeatureStore.java:580)
	at org.geotoolkit.data.shapefile.ShapefileFeatureStore.checkTypeExist(ShapefileFeatureStore.java:215)
	at org.geotoolkit.data.shapefile.ShapefileFeatureStore.getName(ShapefileFeatureStore.java:202)
	at org.geotoolkit.data.shapefile.ShapefileFeatureStore.getNames(ShapefileFeatureStore.java:224)
	at org.geotoolkit.storage.feature.AbstractFeatureStore.components(AbstractFeatureStore.java:148)
	at com.baremaps.pipeline.PipelineTest.readShapefile(PipelineTest.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.opengis.util.NoSuchIdentifierException: No operation method found for name or identifier “Mercator_Auxiliary_Sphere”.
	at org.apache.sis.referencing.operation.transform.DefaultMathTransformFactory.getOperationMethod(DefaultMathTransformFactory.java:474)
	at org.apache.sis.referencing.operation.DefaultCoordinateOperationFactory.getOperationMethod(DefaultCoordinateOperationFactory.java:288)
	at org.apache.sis.io.wkt.GeodeticObjectParser.parseMethod(GeodeticObjectParser.java:1287)
	at org.apache.sis.io.wkt.GeodeticObjectParser.parseDerivingConversion(GeodeticObjectParser.java:1335)
	at org.apache.sis.io.wkt.GeodeticObjectParser.parseProjectedCRS(GeodeticObjectParser.java:2128)
	at org.apache.sis.io.wkt.GeodeticObjectParser.parseCoordinateReferenceSystem(GeodeticObjectParser.java:343)
	at org.apache.sis.io.wkt.GeodeticObjectParser.buildFromTree(GeodeticObjectParser.java:303)
	at org.apache.sis.io.wkt.AbstractParser.createFromWKT(AbstractParser.java:284)
	at org.apache.sis.io.wkt.GeodeticObjectParser.createFromWKT(GeodeticObjectParser.java:260)
	at org.apache.sis.io.wkt.AbstractParser.createFromWKT(AbstractParser.java:244)
	at org.apache.sis.referencing.factory.GeodeticObjectFactory.createFromWKT(GeodeticObjectFactory.java:1672)
	at org.apache.sis.referencing.CRS.fromWKT(CRS.java:309)
	at org.geotoolkit.io.wkt.PrjFiles.read(PrjFiles.java:189)
	... 73 more
```

**Comment by desruisseaux** [comment] 2022-04-21 11:21
The issue is with this `PROJECTION["Mercator_Auxiliary_Sphere"]` part of the WKT. The `PROJECTION` keyword refers to a set of formulas, and I'm not aware of any formulas named "Mercator_Auxiliary_Sphere". A little bit further in the WKT there is a `PARAMETER["Auxiliary_Sphere_Type", 0.0]` element which is also unknown to me. Do you know which software produced this WKT? It does not seem standard to me.

If the intend was to specify the Google map projection (a.k.a. "Pseudo-Mercator") identified by EPSG::3857, the correct projection is: `PROJECTION["Popular Visualisation Pseudo Mercator"]` (source: [EPSG registry](https://epsg.org/crs_3857/WGS-84-Pseudo-Mercator.html)).

**Comment by bchapuis** [comment] 2022-04-21 11:33
Apparently these files are generated with `ogr2ogr`:
https://github.com/fossgis/osmdata/blob/3ab89164acad40ee1db1dacbb7ce777a9245fe9e/scripts/coastline/split.sh#L69

These shapefiles are pretty popular as they are used by OpenStreetMap-Carto and OpenMapTiles.

**Comment by desruisseaux** [comment] 2022-04-21 12:33
After some search on internet, it seems that "Mercator auxiliary sphere" is defined at least by ESRI:

https://desktop.arcgis.com/en/arcmap/latest/map/projections/mercator.htm

Of particular interest the meaning of "Auxiliary Sphere Type" parameter:

* 0 = use semimajor axis or radius of the geographic coordinate system
* 1 = use semiminor axis or radius
* 2 = calculate and use authalic radius
* 3 = use authalic radius and convert geodetic latitudes to authalic latitudes

We need a little bit of development in SIS for adding this support, I will create a JIRA task. Types 0 to 2 are easy, type 3 is more tricky and may not be supported in the first version.

In the meantime, I confirm that type 0 (which is the one used in above WKT) is equivalent to EPSG:3857, so substituting "Mercator_Auxiliary_Sphere" with "Popular Visualisation Pseudo Mercator" and removing `PARAMETER["Auxiliary_Sphere_Type", 0.0]` should work as a temporary workaround.

**Comment by desruisseaux** [comment] 2022-04-21 12:43
Created on SIS issue tracker: https://issues.apache.org/jira/browse/SIS-542

**Comment by desruisseaux** [comment] 2022-04-21 14:53
No, I propose to keep it open until SIS-542 is fixed. Thanks.

**Comment by desruisseaux** [comment] 2022-04-28 09:18
Committed on the `geoapi-4.0` branch. Will be merged to other branches in the next few days.

**Closed by desruisseaux** 2022-04-28 09:18 UTC

**Comment by bchapuis** [comment] 2022-04-28 13:27
Fantastic, thanks a lot.

**Comment by desruisseaux** [comment] 2022-05-04 12:06
Support for type 3 (authalic radius + conversion between geodetic latitudes and authalic latitudes) has been added, so all 4 types should be supported now.
